### ISSUE TITLE
Enable SSL certificate checks

### ISSUE THREAD

**Issue by Pluggi** [thepracticaldeveloper/quboo-sonarqube-plugin#1]
I do not have much Java experience but reading this kind of commits always feels weird.

https://github.com/thepracticaldeveloper/quboo-sonarqube-plugin/commit/78744315f50dc853791c1b8fec81a9ed455431dc#diff-67195b117461b57d851957ce6cd8fee0R32

From my understanding you're basically disabling SSL certificate checks just because some systems may not have Let's Encrypt CA installed. Why don't you just bundle it with the plugin instead?

**Comment by mechero** [comment]
I'll do it soon enough, but that wasn't a blocker to release a first version of the plugin. I keep an eye on it, didn't like it either but at the same time I didn't know yet if I was going to continue with Let's Encrypt certificates.
Thanks for the feedback!

**Comment by mechero** [comment]
This was done already, I forgot to close it...
