### ISSUE TITLE
Ability to limit the scoring to only certain projects

### ISSUE THREAD

**Issue by BermudaLamb** [thepracticaldeveloper/quboo-sonarqube-plugin#7]
Need to be able to select the projects that we want the scoring to show up for. Our environment has several projects that are being managed by SonarQube. However, for Quboo, we want to limit the reporting to only certain projects.

**Comment by mechero** [comment]
Hi @BermudaLamb, 

I think it's a good idea, do you have any suggestion on how to configure the filter? For example, an optional regex in the quboo plugin settings.

**Comment by BermudaLamb** [comment]
I would do it just like the team configuration. Use the API, or whatever is used for the users, to get the list of projects and allow the user to select the projects to be tracked. If more projects are added, then the user could just go in and select the new ones.

**Comment by mechero** [comment]
Hi @BermudaLamb, now you can use inclusion/exclusion lists from the Sonar plugin configuration. The plugin is already available to download from [this link](https://github.com/thepracticaldeveloper/quboo-sonarqube-plugin/releases/tag/v1.3.0). It's also waiting to be processed by the SQ team so it should reach their marketplace soon.

Thanks for the feedback!
